### ISSUE TITLE
Plugin will not uninstall - delete function not present

### ISSUE THREAD

**Issue by shaneholloman** [rrennick/network-wide-menu#2]
I needing delete this as it's causing havoc on my network. I deleted it via via ftp and reinstalled to delete again.

The problem is that its still in the database so reinstalling wont work either as function is redeclared and produces a fatal error

Any thoughts on how to root canal this?

**Comment by shaneholloman** [comment]
here was the solve:
http://premium.wpmudev.org/forums/topic/unable-to-uninstall-network-wide-menus?replies=3#post-544660

**Comment by rrennick** [comment]
> function is redeclared and produces a fatal 

Whenever you get that message it means you have two copies of the same plugin installed and both are active at the same time.

The github issue system is for reporting bugs in software & not intended to be used for support. I'll close the issue.

**Comment by shaneholloman** [comment]
Sorry bout this - I do believe this in fact a bug. I have completely uninstalled and my parent site menus are still dominating the child sites

Trying to get help on this here as well: 
http://premium.wpmudev.org/forums/topic/unable-to-uninstall-network-wide-menus?replies=5#post-546030

**Comment by rrennick** [comment]
Just to be clear, what you are suggesting is that the 28 lines of code in the plugin (https://github.com/rrennick/network-wide-menu/blob/master/ra-network-wide-menu.php) has infected your install like malware or a virus because even though you have removed it, it is still running across your install.

The alternative I suggested above is that you had two copies of the plugin installed (& you have only removed one of them).
